### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by aqualaguna** [DRSchlaubi/contact_picker#12]
fluttercontactpicker: ^3.1.0
crashed my whole app. :(
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2029, result=-1, data=Intent { dat=content://com.android.contacts/contacts/lookup/378i47ad7ed089a02a75.3789r3406-2A2E522A44/4149 flg=0x1 }} to activity {com.falsesilver.app/com.falsesilver.app.MainActivity}: java.lang.NullPointerException: it.getString(it.getColum…mmonDataKinds.Note.NOTE)) must not be null
E/AndroidRuntime(18548): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4905)
E/AndroidRuntime(18548): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4946)
E/AndroidRuntime(18548): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(18548): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(18548): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(18548): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
E/AndroidRuntime(18548): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(18548): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(18548): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/AndroidRuntime(18548): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18548): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(18548): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(18548): Caused by: java.lang.NullPointerException: it.getString(it.getColum…mmonDataKinds.Note.NOTE)) must not be null
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker.getNote(ContactPicker.kt:112)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker.buildContact(ContactPicker.kt:99)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker.access$buildContact(ContactPicker.kt:18)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker$onActivityResult$3.invoke(ContactPicker.kt:47)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker$onActivityResult$3.invoke(ContactPicker.kt:18)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker.processContact(ContactPicker.kt:71)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.ContactPicker.onActivityResult(ContactPicker.kt:47)
E/AndroidRuntime(18548): 	at me.schlaubi.fluttercontactpicker.AbstractPickContext.onActivityResult(AbstractPickContext.kt:15)
E/AndroidRuntime(18548): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(18548): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(18548): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime(18548): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime(18548): 	at android.app.Activity.dispatchActivityResult(Activity.java:8250)
E/AndroidRuntime(18548): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4898)
E/AndroidRuntime(18548): 	... 11 more


```

**Comment by aqualaguna** [comment]
oh btw i downgrade to v2.4.3 and work although there is permission problem.
i'm using permission_handler anyway so its okay. 
wish you fix the problem.

**Comment by DRSchlaubi** [comment]
Strange that it asserts that to not null even if it should be billable have to look into that when I am at home

Also what is the permission issue?

**Comment by DRSchlaubi** [comment]
Coulld you please give me some info about the device used like model, android version etc?

**Comment by aqualaguna** [comment]
Device: Xiaomi 9t Pro
ANDROID VERSION : 10/QKQ1.190825.002
[ro.build.version.base_os]: [Xiaomi/raphael/raphael:10/QKQ1.190825.002/V11.0.3.0.QFKMIXM:user/release-keys]

request issue just it does not ask for permission when permission is not yet granted.

**Comment by DRSchlaubi** [comment]
Yeah the problem is that AOSP android only needs the permission from 11+ and xaiomi needs it earlier that's why I don't request the permission will see if I get to fix that today

**Comment by DRSchlaubi** [comment]
I pushed a bugfix to the bugfix/xaiomi branch could you try whether it works on that
