### ISSUE TITLE
App crashes on Android 11

### ISSUE THREAD

**Issue by samueladekunle** [DRSchlaubi/contact_picker#47]
I am using ```fluttercontactpicker: ^4.5.1```

This line of code

```final contact = await FlutterContactPicker.pickPhoneContact();```

opens the device contact. On selecting a contact, the app crashes and I get this error logged in the debug console.

```
I/Timeline( 9137): Timeline: Activity_launch_request time:528607333
D/AndroidRuntime( 9137): Shutting down VM
E/AndroidRuntime( 9137): FATAL EXCEPTION: main
E/AndroidRuntime( 9137): Process: com.mobile.app, PID: 9137
E/AndroidRuntime( 9137): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2015, result=-1, data=Intent { dat=content://com.android.contacts/data/441 flg=0x1 }} to activity {com.mobile.app/com.mobile.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 9137): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5156)
E/AndroidRuntime( 9137): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5197)
E/AndroidRuntime( 9137): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 9137): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 9137): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 9137): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
E/AndroidRuntime( 9137): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9137): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 9137): 	at android.app.ActivityThread.main(ActivityThread.java:8059)
E/AndroidRuntime( 9137): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9137): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 9137): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime( 9137): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 9137): 	at vn.sendo.flutter.contactpicker.ContactPickerPlugin.onActivityResult(ContactPickerPlugin.java:100)
E/AndroidRuntime( 9137): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
E/AndroidRuntime( 9137): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime( 9137): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
E/AndroidRuntime( 9137): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:916)
E/AndroidRuntime( 9137): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:534)
E/AndroidRuntime( 9137): 	at android.app.Activity.dispatchActivityResult(Activity.java:8524)
E/AndroidRuntime( 9137): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5149)
E/AndroidRuntime( 9137): 	... 11 more
D/OOMEventManagerFK( 9137): checkEventAndDumpForJE: 0
I/Process ( 9137): Sending signal. PID: 9137 SIG: 9
Lost connection to device.
```

Whereas,

```
final contact = await FlutterContactPicker.pickFullContact();
```

does not crash the app.

- Flutter version:
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

OEM: Xiaomi

Android version 11

```compileSdkVersion 30```

```targetSdkVersion 30```

**Comment by ghozay19** [comment]
any updates?

**Comment by samueladekunle** [comment]
@ghozay19, the app was crashing as a result of ```contact_picker``` clashing with some other dependency. To fix the crash, I had to remove that dependency.

**Comment by ashwin-dailype** [comment]
@samueladekunle It'll be really helpful if you can tell me how you were able to figure that it was a dependency clash and figure out the clashing dependency?

**Comment by samueladekunle** [comment]
@ashwin-dailype, the project I was working on at the time had the two dependencies: `contact_picker` and `fluttercontactpicker`; they both performed a similar function. I had to remove the `contact_picker` plugin.
