### ISSUE TITLE
example - pick full contact

### ISSUE THREAD

**Issue by vasilich6107** [DRSchlaubi/contact_picker#52]
Hi.
Thanks for your work.

I'm trying the example project. There is some error happening when I tap "pick full contact"

```
Syncing files to device iPhone 13...
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method pickContact on channel me.schlaubi.contactpicker)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelContactPicker._runCancellable (package:contact_picker_platform_interface/src/method_channel_contact_picker.dart:33:23)
<asynchronous suspension>
#2      MethodChannelContactPicker.pickFullContact (package:contact_picker_platform_interface/src/method_channel_contact_picker.dart:23:28)
<asynchronous suspension>
#3      _MainWidgetState._buildChildren.<anonymous closure> (package:example/main.dart:126:16)
<asynchronous suspension>
```

**Comment by DRSchlaubi** [comment]
> Syncing files to device iPhone 13...

That feature isn't available on iOS

**Comment by vasilich6107** [comment]
Thanks for quick response
